version: 0.2

phases:
  install:
   commands:
     - echo Entering install phase...
    # - echo Nothing to do now
     - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - docker-compose -f production.yml up -d --build
  post_build:
    commands:
      - echo Build completed on `date`
      # - docker-compose push
# docker 사용하려면 aws codebuild에서 권한 체크 해줘야 함

# s3 업로드
artifacts:
  files:
     - "./**/*"
