version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: prd
    container_name: react-intro
    ports:
      - "443:443"
    volumes:
      - ./cert:/etc/ssl/cert:ro
    restart: unless-stopped
    networks:
      - ext-network

networks:
  ext-network:
    external: true
