version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: prd
    container_name: react-intro
    ports:
      - "443:443"
    volumes:
      - ./cert:/etc/ssl/cert:ro
    restart: unless-stopped
    depends_on:
      - ssr-notion
    networks:
      - ext-network

  ssr-notion:
    build:
      context: ./server/notion-service
    container_name: ssr-notion
    environment:
      - PORT=3000
      - NOTION_API_KEY=${NOTION_API_KEY}
      - SPRING_BASE=http://backend-spring-app:8100
    restart: unless-stopped
    networks:
      - ext-network

networks:
  ext-network:
    external: true
