version: '3'
services:
  node:
    build: .
    container_name: 'react-intro'
    volumes:
      - .:/app #로컬과 컨테이너 동기
    command: sh -c "npm install && npm run start_prod"
    ports:
      - "443:3000"
    stdin_open: true
    tty: true